### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Motophan** [Irrational-Encoding-Wizardry/yuuno#44]
Traceback (most recent call last):
  File "/home/gentoo/.local/bin/yuuno", line 8, in <module>
    sys.exit(main())
  File "/home/gentoo/.local/lib/python3.9/site-packages/yuuno/console_scripts.py", line 58, in main
    commands[command]()
  File "/home/gentoo/.local/lib/python3.9/site-packages/yuuno_ipython/commands.py", line 25, in jupyter
    subprocess.check_call([executable, "-m", "notebook.nbextensions", "enable", "--py", "--sys-prefix", "widgetsnbextension"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'notebook.nbextensions', 'enable', '--py', '--sys-prefix', 'widgetsnbextension']' returned non-zero exit status 1.

**Comment by cid-chan** [comment]
https://todo.sr.ht/~cid-chan/yuuno/3
