### ISSUE TITLE
y4mformat setting error

### ISSUE THREAD

**Issue by agkyunromb** [Irrational-Encoding-Wizardry/yuuno#46]
* yuuno version: 1.3.2
* Python version: 3.8.5
* Operating System: Win64

### Description

y4mformat setting error

### What I Did

```
%load_ext yuuno
video_file= "test.avi"
src = core.lsmas.LWLibavSource(video_file)
src_10bit = core.fmtc.bitdepth(src, bits=10,fulls=False,fulld=False) 

%%vspipe --y4m | NVEncC64 -i - --vpy-mt --y4m -o test.mp4
src_10bit.set_output()


Exception in thread Thread-61:
Traceback (most recent call last):
  File "I:\conda\lib\threading.py", line 932, in _bootstrap_inner
    
EncodeWidget(end_time=1611578665, length=3977, start_time=1611578665)
self.run()
  File "I:\conda\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "I:\conda\lib\site-packages\yuuno_ipython\ipy_vs\encode.py", line 185, in _clip_output
    raise e
  File "I:\conda\lib\site-packages\yuuno_ipython\ipy_vs\encode.py", line 179, in _clip_output
    raw_encode(clip, stdin, y4m=y4m, progress=_progress)
  File "I:\conda\lib\site-packages\yuuno_ipython\ipy_vs\outputter.py", line 175, in encode
    y4mformat = y4mformat + 'p' + str(self.format.bits_per_sample)
NameError: name 'self' is not defined
```

```
# please fix line 175 in outputter.py
y4mformat = y4mformat + 'p' + str(clip.format.bits_per_sample)
```

**Comment by cid-chan** [comment]
https://todo.sr.ht/~cid-chan/yuuno/2
