### ISSUE TITLE
Vapoursynth R56 - module 'vapoursynth' has no attribute 'set_message_handler'

### ISSUE THREAD

**Issue by aethanol** [Irrational-Encoding-Wizardry/yuuno#57]
* yuuno version:
* Python version: 3.9.7
* Operating System: docker archlinux

### Description

With most recent release of vapoursynth R56, getting an exception when loading yuuno for the first time.

### What I Did

```
%load_ext yuuno
```
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yuuno/yuuno.py", line 80, in _initialize_extensions
  File "/usr/lib/python3.9/site-packages/yuuno/vs/extension.py", line 227, in initialize
  File "/usr/lib/python3.9/site-packages/yuuno/vs/extension.py", line 167, in initialize_hook
AttributeError: module 'vapoursynth' has no attribute 'set_message_handler'
```

**Comment by eXmendiC** [comment]
Same for me.

**Comment by Bouby308** [comment]
Seems that vapoursynth has removed rather than deprecated 'set_message_handler' from its api.

**Comment by cid-chan** [comment]
Issue has been moved: https://todo.sr.ht/~cid-chan/yuuno/1
